module Hippo::CodeLists
  class ClaimAdjustmentReasonCodes
    def self.[](key)
      @@codes[key]
    end

      @@codes = {
      "1"  => { :code  =>"1",
         :description  => "Deductible Amount",
         :effective_date  => "01/01/1995",
         :deactivation_date  => "",
         :last_modified_date  => "",
         :notes  => ""},
       "2" =>
        {:code =>"2",
         :description =>"Coinsurance Amount",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "3" =>
        {:code =>"3",
         :description =>"Co-payment Amount",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "4" =>
        {:code =>"4",
         :description =>
          "The procedure code is inconsistent with the modifier used or a required modifier is missing. Note: Refer to the 835 Healthcare Policy Identification Segment (loop 2110 Service Payment Information REF), if present.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"09/20/2009",
         :notes =>""},
       "5" =>
        {:code =>"5",
         :description =>
          "The procedure code/bill type is inconsistent with the place of service. Note: Refer to the 835 Healthcare Policy Identification Segment (loop 2110 Service Payment Information REF), if present.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"09/20/2009",
         :notes =>""},
       "6" =>
        {:code =>"6",
         :description =>
          "The procedure/revenue code is inconsistent with the patient's age. Note: Refer to the 835 Healthcare Policy Identification Segment (loop 2110 Service Payment Information REF), if present.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"09/20/2009",
         :notes =>""},
       "7" =>
        {:code =>"7",
         :description =>
          "The procedure/revenue code is inconsistent with the patient's gender. Note: Refer to the 835 Healthcare Policy Identification Segment (loop 2110 Service Payment Information REF), if present.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"09/20/2009",
         :notes =>""},
       "8" =>
        {:code =>"8",
         :description =>
          "The procedure code is inconsistent with the provider type/specialty (taxonomy). Note: Refer to the 835 Healthcare Policy Identification Segment (loop 2110 Service Payment Information REF), if present.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"09/20/2009",
         :notes =>""},
       "9" =>
        {:code =>"9",
         :description =>
          "The diagnosis is inconsistent with the patient's age. Note: Refer to the 835 Healthcare Policy Identification Segment (loop 2110 Service Payment Information REF), if present.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"09/20/2009",
         :notes =>""},
       "10" =>
        {:code =>"10",
         :description =>
          "The diagnosis is inconsistent with the patient's gender. Note: Refer to the 835 Healthcare Policy Identification Segment (loop 2110 Service Payment Information REF), if present.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"09/20/2009",
         :notes =>""},
       "11" =>
        {:code =>"11",
         :description =>
          "The diagnosis is inconsistent with the procedure. Note: Refer to the 835 Healthcare Policy Identification Segment (loop 2110 Service Payment Information REF), if present.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"09/20/2009",
         :notes =>""},
       "12" =>
        {:code =>"12",
         :description =>
          "The diagnosis is inconsistent with the provider type. Note: Refer to the 835 Healthcare Policy Identification Segment (loop 2110 Service Payment Information REF), if present.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"09/20/2009",
         :notes =>""},
       "13" =>
        {:code =>"13",
         :description =>"The date of death precedes the date of service.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "14" =>
        {:code =>"14",
         :description =>"The date of birth follows the date of service.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "15" =>
        {:code =>"15",
         :description =>
          "The authorization number is missing, invalid, or does not apply to the billed services or provider.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"09/30/2007",
         :notes =>""},
       "16" =>
        {:code =>"16",
         :description =>
          "Claim/service lacks information which is needed for adjudication. At least one Remark Code must be provided (may be comprised of either the NCPDP Reject Reason Code, or Remittance Advice Remark Code that is not an ALERT.)",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"09/20/2009",
         :notes =>""},
       "17" =>
        {:code =>"17",
         :description =>
          "Requested information was not provided or was insufficient/incomplete. At least one Remark Code must be provided (may be comprised of either the Remittance Advice Remark Code or NCPDP Reject Reason Code.)",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"07/01/2009",
         :last_modified_date =>"09/21/2008",
         :notes =>""},
       "18" =>
        {:code =>"18",
         :description =>
          "Duplicate claim/service. This change effective 1/1/2013: Exact duplicate claim/service (Use with Group Code OA).",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"10/02/2011",
         :notes =>""},
       "19" =>
        {:code =>"19",
         :description =>
          "This is a work-related injury/illness and thus the liability of the Worker's Compensation Carrier.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"09/30/2007",
         :notes =>""},
       "20" =>
        {:code =>"20",
         :description =>"This injury/illness is covered by the liability carrier.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"09/30/2007",
         :notes =>""},
       "21" =>
        {:code =>"21",
         :description =>
          "This injury/illness is the liability of the no-fault carrier.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"09/30/2007",
         :notes =>""},
       "22" =>
        {:code =>"22",
         :description =>
          "This care may be covered by another payer per coordination of benefits.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"09/30/2007",
         :notes =>""},
       "23" =>
        {:code =>"23",
         :description =>
          "The impact of prior payer(s) adjudication including payments and/or adjustments.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"09/30/2007",
         :notes =>""},
       "24" =>
        {:code =>"24",
         :description =>
          "Charges are covered under a capitation agreement/managed care plan.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"09/30/2007",
         :notes =>""},
       "25" =>
        {:code =>"25",
         :description =>
          "Payment denied. Your Stop loss deductible has not been met.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"04/01/2008",
         :last_modified_date =>"",
         :notes =>""},
       "26" =>
        {:code =>"26",
         :description =>"Expenses incurred prior to coverage.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "27" =>
        {:code =>"27",
         :description =>"Expenses incurred after coverage terminated.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "28" =>
        {:code =>"28",
         :description =>
          "Coverage not in effect at the time the service was provided.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"10/16/2003",
         :last_modified_date =>"",
         :notes =>"Redundant to codes 26&27."},
       "29" =>
        {:code =>"29",
         :description =>"The time limit for filing has expired.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "30" =>
        {:code =>"30",
         :description =>
          "Payment adjusted because the patient has not met the required eligibility, spend down, waiting, or residency requirements.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"02/01/2006",
         :last_modified_date =>"",
         :notes =>""},
       "31" =>
        {:code =>"31",
         :description =>"Patient cannot be identified as our insured.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"09/30/2007",
         :notes =>""},
       "32" =>
        {:code =>"32",
         :description =>
          "Our records indicate that this dependent is not an eligible dependent as defined.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "33" =>
        {:code =>"33",
         :description =>"Insured has no dependent coverage.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"09/30/2007",
         :notes =>""},
       "34" =>
        {:code =>"34",
         :description =>"Insured has no coverage for newborns.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"09/30/2007",
         :notes =>""},
       "35" =>
        {:code =>"35",
         :description =>"Lifetime benefit maximum has been reached.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"10/31/2002",
         :notes =>""},
       "36" =>
        {:code =>"36",
         :description =>"Balance does not exceed co-payment amount.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"10/16/2003",
         :last_modified_date =>"",
         :notes =>""},
       "37" =>
        {:code =>"37",
         :description =>"Balance does not exceed deductible.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"10/16/2003",
         :last_modified_date =>"",
         :notes =>""},
       "38" =>
        {:code =>"38",
         :description =>
          "Services not provided or authorized by designated (network/primary care) providers.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"06/30/2003",
         :notes =>""},
       "39" =>
        {:code =>"39",
         :description =>
          "Services denied at the time authorization/pre-certification was requested.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "40" =>
        {:code =>"40",
         :description =>
          "Charges do not meet qualifications for emergent/urgent care. Note: Refer to the 835 Healthcare Policy Identification Segment (loop 2110 Service Payment Information REF), if present.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"09/20/2009",
         :notes =>""},
       "41" =>
        {:code =>"41",
         :description =>"Discount agreed to in Preferred Provider contract.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"10/16/2003",
         :last_modified_date =>"",
         :notes =>""},
       "42" =>
        {:code =>"42",
         :description =>
          "Charges exceed our fee schedule or maximum allowable amount. (Use CARC 45)",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"06/01/2007",
         :last_modified_date =>"10/31/2006",
         :notes =>""},
       "43" =>
        {:code =>"43",
         :description =>"Gramm-Rudman reduction.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"07/01/2006",
         :last_modified_date =>"",
         :notes =>""},
       "44" =>
        {:code =>"44",
         :description =>"Prompt-pay discount.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "45" =>
        {:code =>"45",
         :description =>
          "Charge exceeds fee schedule/maximum allowable or contracted/legislated fee arrangement. (Use Group Codes PR or CO depending upon liability).",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"10/31/2006",
         :notes =>""},
       "46" =>
        {:code =>"46",
         :description =>"This (these) service(s) is (are) not covered.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"10/16/2003",
         :last_modified_date =>"",
         :notes =>"Use code 96."},
       "47" =>
        {:code =>"47",
         :description =>
          "This (these) diagnosis(es) is (are) not covered, missing, or are invalid.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"02/01/2006",
         :last_modified_date =>"",
         :notes =>""},
       "48" =>
        {:code =>"48",
         :description =>"This (these) procedure(s) is (are) not covered.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"10/16/2003",
         :last_modified_date =>"",
         :notes =>"Use code 96."},
       "49" =>
        {:code =>"49",
         :description =>
          "These are non-covered services because this is a routine exam or screening procedure done in conjunction with a routine exam. Note: Refer to the 835 Healthcare Policy Identification Segment (loop 2110 Service Payment Information  REF), if present.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"09/20/2009",
         :notes =>""},
       "50" =>
        {:code =>"50",
         :description =>
          "These are non-covered services because this is not deemed a 'medical necessity' by the payer. Note: Refer to the 835 Healthcare Policy Identification Segment (loop 2110 Service Payment Information  REF), if present.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"09/20/2009",
         :notes =>""},
       "51" =>
        {:code =>"51",
         :description =>
          "These are non-covered services because this is a pre-existing condition. Note: Refer to the 835 Healthcare Policy Identification Segment (loop 2110 Service Payment Information  REF), if present.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"09/20/2009",
         :notes =>""},
       "52" =>
        {:code =>"52",
         :description =>
          "The referring/prescribing/rendering provider is not eligible to refer/prescribe/order/perform the service billed.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"02/01/2006",
         :last_modified_date =>"",
         :notes =>""},
       "53" =>
        {:code =>"53",
         :description =>
          "Services by an immediate relative or a member of the same household are not covered.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "54" =>
        {:code =>"54",
         :description =>
          "Multiple physicians/assistants are not covered in this case. Note: Refer to the 835 Healthcare Policy Identification Segment (loop 2110 Service Payment Information  REF), if present.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"09/20/2009",
         :notes =>""},
       "55" =>
        {:code =>"55",
         :description =>
          "Procedure/treatment is deemed experimental/investigational by the payer. Note: Refer to the 835 Healthcare Policy Identification Segment (loop 2110 Service Payment Information  REF), if present.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"09/20/2009",
         :notes =>""},
       "56" =>
        {:code =>"56",
         :description =>
          "Procedure/treatment has not been deemed 'proven to be effective' by the payer. Note: Refer to the 835 Healthcare Policy Identification Segment (loop 2110 Service Payment Information  REF), if present.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"09/20/2009",
         :notes =>""},
       "57" =>
        {:code =>"57",
         :description =>
          "Payment denied/reduced because the payer deems the information submitted does not support this level of service, this many services, this length of service, this dosage, or this day's supply.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"06/30/2007",
         :last_modified_date =>"",
         :notes =>"Split into codes 150, 151, 152, 153 and 154."},
       "58" =>
        {:code =>"58",
         :description =>
          "Treatment was deemed by the payer to have been rendered in an inappropriate or invalid place of service. Note: Refer to the 835 Healthcare Policy Identification Segment (loop 2110 Service Payment Information  REF), if present.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"09/20/2009",
         :notes =>""},
       "59" =>
        {:code =>"59",
         :description =>
          "Processed based on multiple or concurrent procedure rules. (For example multiple surgery or diagnostic imaging, concurrent anesthesia.) Note: Refer to the 835 Healthcare Policy Identification Segment (loop 2110 Service Payment Information  REF), if present.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"09/20/2009",
         :notes =>""},
       "60" =>
        {:code =>"60",
         :description =>
          "Charges for outpatient services are not covered when performed within a period of time prior to or after inpatient services.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"06/01/2008",
         :notes =>""},
       "61" =>
        {:code =>"61",
         :description =>
          "Penalty for failure to obtain second surgical opinion. Note: Refer to the 835 Healthcare Policy Identification Segment (loop 2110 Service Payment Information  REF), if present.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"09/20/2009",
         :notes =>""},
       "62" =>
        {:code =>"62",
         :description =>
          "Payment denied/reduced for absence of, or exceeded, pre-certification/authorization.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"04/01/2007",
         :last_modified_date =>"10/31/2006",
         :notes =>""},
       "63" =>
        {:code =>"63",
         :description =>"Correction to a prior claim.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"10/16/2003",
         :last_modified_date =>"",
         :notes =>""},
       "64" =>
        {:code =>"64",
         :description =>"Denial reversed per Medical Review.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"10/16/2003",
         :last_modified_date =>"",
         :notes =>""},
       "65" =>
        {:code =>"65",
         :description =>
          "Procedure code was incorrect. This payment reflects the correct code.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"10/16/2003",
         :last_modified_date =>"",
         :notes =>""},
       "66" =>
        {:code =>"66",
         :description =>"Blood Deductible.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "67" =>
        {:code =>"67",
         :description =>"Lifetime reserve days. (Handled in QTY, QTY01=LA)",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"10/16/2003",
         :last_modified_date =>"",
         :notes =>""},
       "68" =>
        {:code =>"68",
         :description =>"DRG weight. (Handled in CLP12)",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"10/16/2003",
         :last_modified_date =>"",
         :notes =>""},
       "69" =>
        {:code =>"69",
         :description =>"Day outlier amount.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "70" =>
        {:code =>"70",
         :description =>
          "Cost outlier - Adjustment to compensate for additional costs.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"06/30/2001",
         :notes =>""},
       "71" =>
        {:code =>"71",
         :description =>"Primary Payer amount.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"06/30/2000",
         :last_modified_date =>"",
         :notes =>"Use code 23."},
       "72" =>
        {:code =>"72",
         :description =>"Coinsurance day. (Handled in QTY, QTY01=CD)",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"10/16/2003",
         :last_modified_date =>"",
         :notes =>""},
       "73" =>
        {:code =>"73",
         :description =>"Administrative days.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"10/16/2003",
         :last_modified_date =>"",
         :notes =>""},
       "74" =>
        {:code =>"74",
         :description =>"Indirect Medical Education Adjustment.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "75" =>
        {:code =>"75",
         :description =>"Direct Medical Education Adjustment.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "76" =>
        {:code =>"76",
         :description =>"Disproportionate Share Adjustment.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "77" =>
        {:code =>"77",
         :description =>"Covered days. (Handled in QTY, QTY01=CA)",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"10/16/2003",
         :last_modified_date =>"",
         :notes =>""},
       "78" =>
        {:code =>"78",
         :description =>"Non-Covered days/Room charge adjustment.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "79" =>
        {:code =>"79",
         :description =>"Cost Report days. (Handled in MIA15)",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"10/16/2003",
         :last_modified_date =>"",
         :notes =>""},
       "80" =>
        {:code =>"80",
         :description =>"Outlier days. (Handled in QTY, QTY01=OU)",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"10/16/2003",
         :last_modified_date =>"",
         :notes =>""},
       "81" =>
        {:code =>"81",
         :description =>"Discharges.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"10/16/2003",
         :last_modified_date =>"",
         :notes =>""},
       "82" =>
        {:code =>"82",
         :description =>"PIP days.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"10/16/2003",
         :last_modified_date =>"",
         :notes =>""},
       "83" =>
        {:code =>"83",
         :description =>"Total visits.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"10/16/2003",
         :last_modified_date =>"",
         :notes =>""},
       "84" =>
        {:code =>"84",
         :description =>"Capital Adjustment. (Handled in MIA)",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"10/16/2003",
         :last_modified_date =>"",
         :notes =>""},
       "85" =>
        {:code =>"85",
         :description =>"Patient Interest Adjustment (Use Only Group code PR)",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"07/09/2007",
         :notes =>
          "Only use when the payment of interest is the responsibility of the patient."},
       "86" =>
        {:code =>"86",
         :description =>"Statutory Adjustment.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"10/16/2003",
         :last_modified_date =>"",
         :notes =>"Duplicative of code 45."},
       "87" =>
        {:code =>"87",
         :description =>"Transfer amount.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"01/01/2012",
         :last_modified_date =>"09/20/2009",
         :notes =>""},
       "88" =>
        {:code =>"88",
         :description =>
          "Adjustment amount represents collection against receivable created in prior overpayment.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"06/30/2007",
         :last_modified_date =>"",
         :notes =>""},
       "89" =>
        {:code =>"89",
         :description =>"Professional fees removed from charges.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "90" =>
        {:code =>"90",
         :description =>
          "Ingredient cost adjustment. Note: To be used for pharmaceuticals only.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"07/01/2009",
         :notes =>""},
       "91" =>
        {:code =>"91",
         :description =>"Dispensing fee adjustment.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "92" =>
        {:code =>"92",
         :description =>"Claim Paid in full.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"10/16/2003",
         :last_modified_date =>"",
         :notes =>""},
       "93" =>
        {:code =>"93",
         :description =>"No Claim level Adjustments.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"10/16/2003",
         :last_modified_date =>"",
         :notes =>"As of 004010, CAS at the claim level is optional."},
       "94" =>
        {:code =>"94",
         :description =>"Processed in Excess of charges.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "95" =>
        {:code =>"95",
         :description =>"Plan procedures not followed.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"09/30/2007",
         :notes =>""},
       "96" =>
        {:code =>"96",
         :description =>
          "Non-covered charge(s). At least one Remark Code must be provided (may be comprised of either the NCPDP Reject Reason Code, or Remittance Advice Remark Code that is not an ALERT.) Note: Refer to the 835 Healthcare Policy Identification Segment (loop 2110 Service Payment Information  REF), if present.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"09/20/2009",
         :notes =>""},
       "97" =>
        {:code =>"97",
         :description =>
          "The benefit for this service is included in the payment/allowance for another service/procedure that has already been adjudicated. Note: Refer to the 835 Healthcare Policy Identification Segment (loop 2110 Service Payment Information  REF), if present.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"09/20/2009",
         :notes =>""},
       "98" =>
        {:code =>"98",
         :description =>
          "The hospital must file the Medicare claim for this inpatient non-physician service.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"10/16/2003",
         :last_modified_date =>"",
         :notes =>""},
       "99" =>
        {:code =>"99",
         :description =>"Medicare Secondary Payer Adjustment Amount.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"10/16/2003",
         :last_modified_date =>"",
         :notes =>""},
       "100" =>
        {:code =>"100",
         :description =>
          "Payment made to patient/insured/responsible party/employer.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"01/27/2008",
         :notes =>""},
       "101" =>
        {:code =>"101",
         :description =>
          "Predetermination: anticipated payment upon completion of services or claim adjudication.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"02/28/1999",
         :notes =>""},
       "102" =>
        {:code =>"102",
         :description =>"Major Medical Adjustment.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "103" =>
        {:code =>"103",
         :description =>
          "Provider promotional discount (e.g., Senior citizen discount).",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"06/30/2001",
         :notes =>""},
       "104" =>
        {:code =>"104",
         :description =>"Managed care withholding.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "105" =>
        {:code =>"105",
         :description =>"Tax withholding.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "106" =>
        {:code =>"106",
         :description =>"Patient payment option/election not in effect.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "107" =>
        {:code =>"107",
         :description =>
          "The related or qualifying claim/service was not identified on this claim. Note: Refer to the 835 Healthcare Policy Identification Segment (loop 2110 Service Payment Information  REF), if present.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"09/20/2009",
         :notes =>""},
       "108" =>
        {:code =>"108",
         :description =>
          "Rent/purchase guidelines were not met. Note: Refer to the 835 Healthcare Policy Identification Segment (loop 2110 Service Payment Information  REF), if present.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"09/20/2009",
         :notes =>""},
       "109" =>
        {:code =>"109",
         :description =>
          "Claim not covered by this payer/contractor. You must send the claim to the correct payer/contractor.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "110" =>
        {:code =>"110",
         :description =>"Billing date predates service date.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "111" =>
        {:code =>"111",
         :description =>"Not covered unless the provider accepts assignment.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "112" =>
        {:code =>"112",
         :description =>
          "Service not furnished directly to the patient and/or not documented.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"09/30/2007",
         :notes =>""},
       "113" =>
        {:code =>"113",
         :description =>
          "Payment denied because service/procedure was provided outside the United States or as a result of war.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"06/30/2007",
         :last_modified_date =>"02/28/2001",
         :notes =>"Use Codes 157, 158 or 159."},
       "114" =>
        {:code =>"114",
         :description =>
          "Procedure/product not approved by the Food and Drug Administration.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "115" =>
        {:code =>"115",
         :description =>"Procedure postponed, canceled, or delayed.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"09/30/2007",
         :notes =>""},
       "116" =>
        {:code =>"116",
         :description =>
          "The advance indemnification notice signed by the patient did not comply with requirements.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"09/30/2007",
         :notes =>""},
       "117" =>
        {:code =>"117",
         :description =>
          "Transportation is only covered to the closest facility that can provide the necessary care.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"09/30/2007",
         :notes =>""},
       "118" =>
        {:code =>"118",
         :description =>"ESRD network support adjustment.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"09/30/2007",
         :notes =>""},
       "119" =>
        {:code =>"119",
         :description =>
          "Benefit maximum for this time period or occurrence has been reached.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"02/29/2004",
         :notes =>""},
       "120" =>
        {:code =>"120",
         :description =>"Patient is covered by a managed care plan.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"06/30/2007",
         :last_modified_date =>"",
         :notes =>"Use code 24."},
       "121" =>
        {:code =>"121",
         :description =>
          "Indemnification adjustment - compensation for outstanding member responsibility.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"09/30/2007",
         :notes =>""},
       "122" =>
        {:code =>"122",
         :description =>"Psychiatric reduction.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "123" =>
        {:code =>"123",
         :description =>"Payer refund due to overpayment.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"06/30/2007",
         :last_modified_date =>"",
         :notes =>
          "Refer to implementation guide for proper handling of reversals."},
       "124" =>
        {:code =>"124",
         :description =>"Payer refund amount - not our patient.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"06/30/2007",
         :last_modified_date =>"06/30/1999",
         :notes =>
          "Refer to implementation guide for proper handling of reversals."},
       "125" =>
        {:code =>"125",
         :description =>
          "Submission/billing error(s). At least one Remark Code must be provided (may be comprised of either the NCPDP Reject Reason Code, or Remittance Advice Remark Code that is not an ALERT.)",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"09/20/2009",
         :notes =>""},
       "126" =>
        {:code =>"126",
         :description =>"Deductible -- Major Medical",
         :effective_date =>"02/28/1997",
         :deactivation_date =>"04/01/2008",
         :last_modified_date =>"09/30/2007",
         :notes =>"Use Group Code PR and code 1."},
       "127" =>
        {:code =>"127",
         :description =>"Coinsurance -- Major Medical",
         :effective_date =>"02/28/1997",
         :deactivation_date =>"04/01/2008",
         :last_modified_date =>"09/30/2007",
         :notes =>"Use Group Code PR and code 2."},
       "128" =>
        {:code =>"128",
         :description =>"Newborn's services are covered in the mother's Allowance.",
         :effective_date =>"02/28/1997",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "129" =>
        {:code =>"129",
         :description =>
          "Prior processing information appears incorrect. At least one Remark Code must be provided (may be comprised of either the NCPDP Reject Reason Code, or Remittance Advice Remark Code that is not an ALERT.)",
         :effective_date =>"02/28/1997",
         :deactivation_date =>"",
         :last_modified_date =>"01/30/2011",
         :notes =>""},
       "130" =>
        {:code =>"130",
         :description =>"Claim submission fee.",
         :effective_date =>"02/28/1997",
         :deactivation_date =>"",
         :last_modified_date =>"06/30/2001",
         :notes =>""},
       "131" =>
        {:code =>"131",
         :description =>"Claim specific negotiated discount.",
         :effective_date =>"02/28/1997",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "132" =>
        {:code =>"132",
         :description =>"Prearranged demonstration project adjustment.",
         :effective_date =>"02/28/1997",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "133" =>
        {:code =>"133",
         :description =>
          "The disposition of this claim/service is pending further review.",
         :effective_date =>"02/28/1997",
         :deactivation_date =>"",
         :last_modified_date =>"10/31/1999",
         :notes =>""},
       "134" =>
        {:code =>"134",
         :description =>"Technical fees removed from charges.",
         :effective_date =>"10/31/1998",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "135" =>
        {:code =>"135",
         :description =>"Interim bills cannot be processed.",
         :effective_date =>"10/31/1998",
         :deactivation_date =>"",
         :last_modified_date =>"09/30/2007",
         :notes =>""},
       "136" =>
        {:code =>"136",
         :description =>
          "Failure to follow prior payer's coverage rules. (Use Group Code OA).",
         :effective_date =>"10/31/1998",
         :deactivation_date =>"",
         :last_modified_date =>"09/30/2007",
         :notes =>""},
       "137" =>
        {:code =>"137",
         :description =>
          "Regulatory Surcharges, Assessments, Allowances or Health Related Taxes.",
         :effective_date =>"02/28/1999",
         :deactivation_date =>"",
         :last_modified_date =>"09/30/2007",
         :notes =>""},
       "138" =>
        {:code =>"138",
         :description =>"Appeal procedures not followed or time limits not met.",
         :effective_date =>"06/30/1999",
         :deactivation_date =>"",
         :last_modified_date =>"09/30/2007",
         :notes =>""},
       "139" =>
        {:code =>"139",
         :description =>
          "Contracted funding agreement - Subscriber is employed by the provider of services.",
         :effective_date =>"06/30/1999",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "140" =>
        {:code =>"140",
         :description =>
          "Patient/Insured health identification number and name do not match.",
         :effective_date =>"06/30/1999",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "141" =>
        {:code =>"141",
         :description =>"Claim spans eligible and ineligible periods of coverage.",
         :effective_date =>"06/30/1999",
         :deactivation_date =>"07/01/2012",
         :last_modified_date =>"09/30/2007",
         :notes =>""},
       "142" =>
        {:code =>"142",
         :description =>"Monthly Medicaid patient liability amount.",
         :effective_date =>"06/30/2000",
         :deactivation_date =>"",
         :last_modified_date =>"09/30/2007",
         :notes =>""},
       "143" =>
        {:code =>"143",
         :description =>"Portion of payment deferred.",
         :effective_date =>"02/28/2001",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "144" =>
        {:code =>"144",
         :description =>"Incentive adjustment, e.g. preferred product/service.",
         :effective_date =>"06/30/2001",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "145" =>
        {:code =>"145",
         :description =>"Premium payment withholding",
         :effective_date =>"06/30/2002",
         :deactivation_date =>"04/01/2008",
         :last_modified_date =>"09/30/2007",
         :notes =>"Use Group Code CO and code 45."},
       "146" =>
        {:code =>"146",
         :description =>
          "Diagnosis was invalid for the date(s) of service reported.",
         :effective_date =>"06/30/2002",
         :deactivation_date =>"",
         :last_modified_date =>"09/30/2007",
         :notes =>""},
       "147" =>
        {:code =>"147",
         :description =>
          "Provider contracted/negotiated rate expired or not on file.",
         :effective_date =>"06/30/2002",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "148" =>
        {:code =>"148",
         :description =>
          "Information from another provider was not provided or was insufficient/incomplete. At least one Remark Code must be provided (may be comprised of either the NCPDP Reject Reason Code, or Remittance Advice Remark Code that is not an ALERT.)",
         :effective_date =>"06/30/2002",
         :deactivation_date =>"",
         :last_modified_date =>"09/20/2009",
         :notes =>""},
       "149" =>
        {:code =>"149",
         :description =>
          "Lifetime benefit maximum has been reached for this service/benefit category.",
         :effective_date =>"10/31/2002",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "150" =>
        {:code =>"150",
         :description =>
          "Payer deems the information submitted does not support this level of service.",
         :effective_date =>"10/31/2002",
         :deactivation_date =>"",
         :last_modified_date =>"09/30/2007",
         :notes =>""},
       "151" =>
        {:code =>"151",
         :description =>
          "Payment adjusted because the payer deems the information submitted does not support this many/frequency of services.",
         :effective_date =>"10/31/2002",
         :deactivation_date =>"",
         :last_modified_date =>"01/27/2008",
         :notes =>""},
       "152" =>
        {:code =>"152",
         :description =>
          "Payer deems the information submitted does not support this length of service. Note: Refer to the 835 Healthcare Policy Identification Segment (loop 2110 Service Payment Information  REF), if present.",
         :effective_date =>"10/31/2002",
         :deactivation_date =>"",
         :last_modified_date =>"09/20/2009",
         :notes =>""},
       "153" =>
        {:code =>"153",
         :description =>
          "Payer deems the information submitted does not support this dosage.",
         :effective_date =>"10/31/2002",
         :deactivation_date =>"",
         :last_modified_date =>"09/30/2007",
         :notes =>""},
       "154" =>
        {:code =>"154",
         :description =>
          "Payer deems the information submitted does not support this day's supply.",
         :effective_date =>"10/31/2002",
         :deactivation_date =>"",
         :last_modified_date =>"09/30/2007",
         :notes =>""},
       "155" =>
        {:code =>"155",
         :description =>"Patient refused the service/procedure.",
         :effective_date =>"06/30/2003",
         :deactivation_date =>"",
         :last_modified_date =>"09/30/2007",
         :notes =>""},
       "156" =>
        {:code =>"156",
         :description =>"Flexible spending account payments. Note: Use code 187.",
         :effective_date =>"09/30/2003",
         :deactivation_date =>"10/01/2009",
         :last_modified_date =>"01/25/2009",
         :notes =>""},
       "157" =>
        {:code =>"157",
         :description =>
          "Service/procedure was provided as a result of an act of war.",
         :effective_date =>"09/30/2003",
         :deactivation_date =>"",
         :last_modified_date =>"09/30/2007",
         :notes =>""},
       "158" =>
        {:code =>"158",
         :description =>
          "Service/procedure was provided outside of the United States.",
         :effective_date =>"09/30/2003",
         :deactivation_date =>"",
         :last_modified_date =>"09/30/2007",
         :notes =>""},
       "159" =>
        {:code =>"159",
         :description =>"Service/procedure was provided as a result of terrorism.",
         :effective_date =>"09/30/2003",
         :deactivation_date =>"",
         :last_modified_date =>"09/30/2007",
         :notes =>""},
       "160" =>
        {:code =>"160",
         :description =>
          "Injury/illness was the result of an activity that is a benefit exclusion.",
         :effective_date =>"09/30/2003",
         :deactivation_date =>"",
         :last_modified_date =>"09/30/2007",
         :notes =>""},
       "161" =>
        {:code =>"161",
         :description =>"Provider performance bonus",
         :effective_date =>"02/29/2004",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "162" =>
        {:code =>"162",
         :description =>
          "State-mandated Requirement for Property and Casualty, see Claim Payment Remarks Code for specific explanation.",
         :effective_date =>"02/29/2004",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "163" =>
        {:code =>"163",
         :description =>"Attachment referenced on the claim was not received.",
         :effective_date =>"06/30/2004",
         :deactivation_date =>"",
         :last_modified_date =>"09/30/2007",
         :notes =>""},
       "164" =>
        {:code =>"164",
         :description =>
          "Attachment referenced on the claim was not received in a timely fashion.",
         :effective_date =>"06/30/2004",
         :deactivation_date =>"",
         :last_modified_date =>"09/30/2007",
         :notes =>""},
       "165" =>
        {:code =>"165",
         :description =>"Referral absent or exceeded.",
         :effective_date =>"10/31/2004",
         :deactivation_date =>"",
         :last_modified_date =>"09/30/2007",
         :notes =>""},
       "166" =>
        {:code =>"166",
         :description =>
          "These services were submitted after this payers responsibility for processing claims under this plan ended.",
         :effective_date =>"02/28/2005",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "167" =>
        {:code =>"167",
         :description =>
          "This (these) diagnosis(es) is (are) not covered. Note: Refer to the 835 Healthcare Policy Identification Segment (loop 2110 Service Payment Information  REF), if present.",
         :effective_date =>"06/30/2005",
         :deactivation_date =>"",
         :last_modified_date =>"09/20/2009",
         :notes =>""},
       "168" =>
        {:code =>"168",
         :description =>
          "Service(s) have been considered under the patient's medical plan. Benefits are not available under this dental plan.",
         :effective_date =>"06/30/2005",
         :deactivation_date =>"",
         :last_modified_date =>"09/30/2007",
         :notes =>""},
       "169" =>
        {:code =>"169",
         :description =>"Alternate benefit has been provided.",
         :effective_date =>"06/30/2005",
         :deactivation_date =>"",
         :last_modified_date =>"09/30/2007",
         :notes =>""},
       "170" =>
        {:code =>"170",
         :description =>
          "Payment is denied when performed/billed by this type of provider. Note: Refer to the 835 Healthcare Policy Identification Segment (loop 2110 Service Payment Information  REF), if present.",
         :effective_date =>"06/30/2005",
         :deactivation_date =>"",
         :last_modified_date =>"09/20/2009",
         :notes =>""},
       "171" =>
        {:code =>"171",
         :description =>
          "Payment is denied when performed/billed by this type of provider in this type of facility. Note: Refer to the 835 Healthcare Policy Identification Segment (loop 2110 Service Payment Information  REF), if present.",
         :effective_date =>"06/30/2005",
         :deactivation_date =>"",
         :last_modified_date =>"09/20/2009",
         :notes =>""},
       "172" =>
        {:code =>"172",
         :description =>
          "Payment is adjusted when performed/billed by a provider of this specialty. Note: Refer to the 835 Healthcare Policy Identification Segment (loop 2110 Service Payment Information  REF), if present.",
         :effective_date =>"06/30/2005",
         :deactivation_date =>"",
         :last_modified_date =>"09/20/2009",
         :notes =>""},
       "173" =>
        {:code =>"173",
         :description =>"Service was not prescribed by a physician.",
         :effective_date =>"06/30/2005",
         :deactivation_date =>"",
         :last_modified_date =>"09/30/2007",
         :notes =>""},
       "174" =>
        {:code =>"174",
         :description =>"Service was not prescribed prior to delivery.",
         :effective_date =>"06/30/2005",
         :deactivation_date =>"",
         :last_modified_date =>"09/30/2007",
         :notes =>""},
       "175" =>
        {:code =>"175",
         :description =>"Prescription is incomplete.",
         :effective_date =>"06/30/2005",
         :deactivation_date =>"",
         :last_modified_date =>"09/30/2007",
         :notes =>""},
       "176" =>
        {:code =>"176",
         :description =>"Prescription is not current.",
         :effective_date =>"06/30/2005",
         :deactivation_date =>"",
         :last_modified_date =>"09/30/2007",
         :notes =>""},
       "177" =>
        {:code =>"177",
         :description =>
          "Patient has not met the required eligibility requirements.",
         :effective_date =>"06/30/2005",
         :deactivation_date =>"",
         :last_modified_date =>"09/30/2007",
         :notes =>""},
       "178" =>
        {:code =>"178",
         :description =>"Patient has not met the required spend down requirements.",
         :effective_date =>"06/30/2005",
         :deactivation_date =>"",
         :last_modified_date =>"09/30/2007",
         :notes =>""},
       "179" =>
        {:code =>"179",
         :description =>
          "Patient has not met the required waiting requirements. Note: Refer to the 835 Healthcare Policy Identification Segment (loop 2110 Service Payment Information  REF), if present.",
         :effective_date =>"06/30/2005",
         :deactivation_date =>"",
         :last_modified_date =>"09/20/2009",
         :notes =>""},
       "180" =>
        {:code =>"180",
         :description =>"Patient has not met the required residency requirements.",
         :effective_date =>"06/30/2005",
         :deactivation_date =>"",
         :last_modified_date =>"09/30/2007",
         :notes =>""},
       "181" =>
        {:code =>"181",
         :description =>"Procedure code was invalid on the date of service.",
         :effective_date =>"06/30/2005",
         :deactivation_date =>"",
         :last_modified_date =>"09/30/2007",
         :notes =>""},
       "182" =>
        {:code =>"182",
         :description =>"Procedure modifier was invalid on the date of service.",
         :effective_date =>"06/30/2005",
         :deactivation_date =>"",
         :last_modified_date =>"09/30/2007",
         :notes =>""},
       "183" =>
        {:code =>"183",
         :description =>
          "The referring provider is not eligible to refer the service billed. Note: Refer to the 835 Healthcare Policy Identification Segment (loop 2110 Service Payment Information  REF), if present.",
         :effective_date =>"06/30/2005",
         :deactivation_date =>"",
         :last_modified_date =>"09/20/2009",
         :notes =>""},
       "184" =>
        {:code =>"184",
         :description =>
          "The prescribing/ordering provider is not eligible to prescribe/order the service billed. Note: Refer to the 835 Healthcare Policy Identification Segment (loop 2110 Service Payment Information  REF), if present.",
         :effective_date =>"06/30/2005",
         :deactivation_date =>"",
         :last_modified_date =>"09/20/2009",
         :notes =>""},
       "185" =>
        {:code =>"185",
         :description =>
          "The rendering provider is not eligible to perform the service billed. Note: Refer to the 835 Healthcare Policy Identification Segment (loop 2110 Service Payment Information  REF), if present.",
         :effective_date =>"06/30/2005",
         :deactivation_date =>"",
         :last_modified_date =>"09/20/2009",
         :notes =>""},
       "186" =>
        {:code =>"186",
         :description =>"Level of care change adjustment.",
         :effective_date =>"06/30/2005",
         :deactivation_date =>"",
         :last_modified_date =>"09/30/2007",
         :notes =>""},
       "187" =>
        {:code =>"187",
         :description =>
          "Consumer Spending Account payments (includes but is not limited to Flexible Spending Account, Health Savings Account, Health Reimbursement Account, etc.)",
         :effective_date =>"06/30/2005",
         :deactivation_date =>"",
         :last_modified_date =>"01/25/2009",
         :notes =>""},
       "188" =>
        {:code =>"188",
         :description =>
          "This product/procedure is only covered when used according to FDA recommendations.",
         :effective_date =>"06/30/2005",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "189" =>
        {:code =>"189",
         :description =>
          "'Not otherwise classified' or 'unlisted' procedure code (CPT/HCPCS) was billed when there is a specific procedure code for this procedure/service",
         :effective_date =>"06/30/2005",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "190" =>
        {:code =>"190",
         :description =>
          "Payment is included in the allowance for a Skilled Nursing Facility (SNF) qualified stay.",
         :effective_date =>"10/31/2005",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "191" =>
        {:code =>"191",
         :description =>
          "Not a work related injury/illness and thus not the liability of the workers' compensation carrier Note: If adjustment is at the Claim Level, the payer must send and the provider should refer to the 835 Insurance Policy Number Segment (Loop 2100 Other Claim Related Information REF qualifier 'IG') for the jurisdictional regulation. If adjustment is at the Line Level, the payer must send and the provider should refer to the 835 Healthcare Policy Identification Segment (loop 2110 Service Payment information REF)",
         :effective_date =>"10/31/2005",
         :deactivation_date =>"",
         :last_modified_date =>"10/17/2010",
         :notes =>""},
       "192" =>
        {:code =>"192",
         :description =>
          "Non standard adjustment code from paper remittance. Note: This code is to be used by providers/payers providing Coordination of Benefits information to another payer in the 837 transaction only. This code is only used when the non-standard code cannot be reasonably mapped to an existing Claims Adjustment Reason Code, specifically Deductible, Coinsurance and Co-payment.",
         :effective_date =>"10/31/2005",
         :deactivation_date =>"",
         :last_modified_date =>"09/30/2007",
         :notes =>""},
       "193" =>
        {:code =>"193",
         :description =>
          "Original payment decision is being maintained. Upon review, it was determined that this claim was processed properly.",
         :effective_date =>"02/28/2006",
         :deactivation_date =>"",
         :last_modified_date =>"01/27/2008",
         :notes =>""},
       "194" =>
        {:code =>"194",
         :description =>
          "Anesthesia performed by the operating physician, the assistant surgeon or the attending physician.",
         :effective_date =>"02/28/2006",
         :deactivation_date =>"",
         :last_modified_date =>"09/30/2007",
         :notes =>""},
       "195" =>
        {:code =>"195",
         :description =>
          "Refund issued to an erroneous priority payer for this claim/service.",
         :effective_date =>"02/28/2006",
         :deactivation_date =>"",
         :last_modified_date =>"09/30/2007",
         :notes =>""},
       "196" =>
        {:code =>"196",
         :description =>
          "Claim/service denied based on prior payer's coverage determination.",
         :effective_date =>"06/30/2006",
         :deactivation_date =>"02/01/2007",
         :last_modified_date =>"",
         :notes =>"Use code 136."},
       "197" =>
        {:code =>"197",
         :description =>"Precertification/authorization/notification absent.",
         :effective_date =>"10/31/2006",
         :deactivation_date =>"",
         :last_modified_date =>"09/30/2007",
         :notes =>""},
       "198" =>
        {:code =>"198",
         :description =>"Precertification/authorization exceeded.",
         :effective_date =>"10/31/2006",
         :deactivation_date =>"",
         :last_modified_date =>"09/30/2007",
         :notes =>""},
       "199" =>
        {:code =>"199",
         :description =>"Revenue code and Procedure code do not match.",
         :effective_date =>"10/31/2006",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "200" =>
        {:code =>"200",
         :description =>"Expenses incurred during lapse in coverage",
         :effective_date =>"10/31/2006",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "201" =>
        {:code =>"201",
         :description =>
          "Workers Compensation case settled. Patient is responsible for amount of this claim/service through WC 'Medicare set aside arrangement' or other agreement. (Use group code PR).",
         :effective_date =>"10/31/2006",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "202" =>
        {:code =>"202",
         :description =>"Non-covered personal comfort or convenience services.",
         :effective_date =>"02/28/2007",
         :deactivation_date =>"",
         :last_modified_date =>"09/30/2007",
         :notes =>""},
       "203" =>
        {:code =>"203",
         :description =>"Discontinued or reduced service.",
         :effective_date =>"02/28/2007",
         :deactivation_date =>"",
         :last_modified_date =>"09/30/2007",
         :notes =>""},
       "204" =>
        {:code =>"204",
         :description =>
          "This service/equipment/drug is not covered under the patient's current benefit plan",
         :effective_date =>"02/28/2007",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "205" =>
        {:code =>"205",
         :description =>"Pharmacy discount card processing fee",
         :effective_date =>"07/09/2007",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "206" =>
        {:code =>"206",
         :description =>"National Provider Identifier - missing.",
         :effective_date =>"07/09/2007",
         :deactivation_date =>"",
         :last_modified_date =>"09/30/2007",
         :notes =>""},
       "207" =>
        {:code =>"207",
         :description =>"National Provider identifier - Invalid format",
         :effective_date =>"07/09/2007",
         :deactivation_date =>"",
         :last_modified_date =>"06/01/2008",
         :notes =>""},
       "208" =>
        {:code =>"208",
         :description =>"National Provider Identifier - Not matched.",
         :effective_date =>"07/09/2007",
         :deactivation_date =>"",
         :last_modified_date =>"09/30/2007",
         :notes =>""},
       "209" =>
        {:code =>"209",
         :description =>
          "Per regulatory or other agreement. The provider cannot collect this amount from the patient. However, this amount may be billed to subsequent payer. Refund to patient if collected. (Use Group code OA)",
         :effective_date =>"07/09/2007",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "210" =>
        {:code =>"210",
         :description =>
          "Payment adjusted because pre-certification/authorization not received in a timely fashion",
         :effective_date =>"07/09/2007",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "211" =>
        {:code =>"211",
         :description =>
          "National Drug Codes (NDC) not eligible for rebate, are not covered.",
         :effective_date =>"07/09/2007",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "212" =>
        {:code =>"212",
         :description =>"Administrative surcharges are not covered",
         :effective_date =>"11/05/2007",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "213" =>
        {:code =>"213",
         :description =>
          "Non-compliance with the physician self referral prohibition legislation or payer policy.",
         :effective_date =>"01/27/2008",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "214" =>
        {:code =>"214",
         :description =>
          "Workers' Compensation claim adjudicated as non-compensable. This Payer not liable for claim or service/treatment. Note: If adjustment is at the Claim Level, the payer must send and the provider should refer to the 835 Insurance Policy Number Segment (Loop 2100 Other Claim Related Information REF qualifier 'IG') for the jurisdictional regulation. If adjustment is at the Line Level, the payer must send and the provider should refer to the 835 Healthcare Policy Identification Segment (loop 2110 Service Payment information REF). To be used for Workers' Compensation only",
         :effective_date =>"01/27/2008",
         :deactivation_date =>"",
         :last_modified_date =>"10/17/2010",
         :notes =>""},
       "215" =>
        {:code =>"215",
         :description =>"Based on subrogation of a third party settlement",
         :effective_date =>"01/27/2008",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "216" =>
        {:code =>"216",
         :description =>"Based on the findings of a review organization",
         :effective_date =>"01/27/2008",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "217" =>
        {:code =>"217",
         :description =>
          "Based on payer reasonable and customary fees. No maximum allowable defined by legislated fee arrangement. (Note: To be used for Workers' Compensation only)",
         :effective_date =>"01/27/2008",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "218" =>
        {:code =>"218",
         :description =>
          "Based on entitlement to benefits. Note: If adjustment is at the Claim Level, the payer must send and the provider should refer to the 835 Insurance Policy Number Segment (Loop 2100 Other Claim Related Information REF qualifier 'IG') for the jurisdictional regulation. If adjustment is at the Line Level, the payer must send and the provider should refer to the 835 Healthcare Policy Identification Segment (loop 2110 Service Payment information REF). To be used for Workers' Compensation only",
         :effective_date =>"01/27/2008",
         :deactivation_date =>"",
         :last_modified_date =>"10/17/2010",
         :notes =>""},
       "219" =>
        {:code =>"219",
         :description =>
          "Based on extent of injury. Note: If adjustment is at the Claim Level, the payer must send and the provider should refer to the 835 Insurance Policy Number Segment (Loop 2100 Other Claim Related Information REF qualifier 'IG') for the jurisdictional regulation. If adjustment is at the Line Level, the payer must send and the provider should refer to the 835 Healthcare Policy Identification Segment (loop 2110 Service Payment information REF).",
         :effective_date =>"01/27/2008",
         :deactivation_date =>"",
         :last_modified_date =>"10/17/2010",
         :notes =>""},
       "220" =>
        {:code =>"220",
         :description =>
          "The applicable fee schedule does not contain the billed code. Please resubmit a bill with the appropriate fee schedule code(s) that best describe the service(s) provided and supporting documentation if required. (Note: To be used for Workers' Compensation only)",
         :effective_date =>"01/27/2008",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "221" =>
        {:code =>"221",
         :description =>
          "Workers' Compensation claim is under investigation. Note: If adjustment is at the Claim Level, the payer must send and the provider should refer to the 835 Insurance Policy Number Segment (Loop 2100 Other Claim Related Information REF qualifier 'IG') for the jurisdictional regulation. If adjustment is at the Line Level, the payer must send and the provider should refer to the 835 Healthcare Policy Identification Segment (loop 2110 Service Payment information REF).",
         :effective_date =>"01/27/2008",
         :deactivation_date =>"",
         :last_modified_date =>"10/17/2010",
         :notes =>""},
       "222" =>
        {:code =>"222",
         :description =>
          "Exceeds the contracted maximum number of hours/days/units by this provider for this period. This is not patient specific. Note: Refer to the 835 Healthcare Policy Identification Segment (loop 2110 Service Payment Information  REF), if present.",
         :effective_date =>"06/01/2008",
         :deactivation_date =>"",
         :last_modified_date =>"09/20/2009",
         :notes =>""},
       "223" =>
        {:code =>"223",
         :description =>
          "Adjustment code for mandated federal, state or local law/regulation that is not already covered by another code and is mandated before a new code can be created.",
         :effective_date =>"06/01/2008",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "224" =>
        {:code =>"224",
         :description =>
          "Patient identification compromised by identity theft. Identity verification required for processing this and future claims.",
         :effective_date =>"06/01/2008",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "225" =>
        {:code =>"225",
         :description =>
          "Penalty or Interest Payment by Payer (Only used for plan to plan encounter reporting within the 837)",
         :effective_date =>"06/01/2008",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "226" =>
        {:code =>"226",
         :description =>
          "Information requested from the Billing/Rendering Provider was not provided or was insufficient/incomplete. At least one Remark Code must be provided (may be comprised of either the NCPDP Reject Reason Code, or Remittance Advice Remark Code that is not an ALERT.)",
         :effective_date =>"09/21/2008",
         :deactivation_date =>"",
         :last_modified_date =>"09/20/2009",
         :notes =>""},
       "227" =>
        {:code =>"227",
         :description =>
          "Information requested from the patient/insured/responsible party was not provided or was insufficient/incomplete. At least one Remark Code must be provided (may be comprised of either the NCPDP Reject Reason Code, or Remittance Advice Remark Code that is not an ALERT.)",
         :effective_date =>"09/21/2008",
         :deactivation_date =>"",
         :last_modified_date =>"09/20/2009",
         :notes =>""},
       "228" =>
        {:code =>"228",
         :description =>
          "Denied for failure of this provider, another provider or the subscriber to supply requested information to a previous payer for their adjudication",
         :effective_date =>"09/21/2008",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "229" =>
        {:code =>"229",
         :description =>
          "Partial charge amount not considered by Medicare due to the initial claim Type of Bill being 12X. Note: This code can only be used in the 837 transaction to convey Coordination of Benefits information when the secondary payer's cost avoidance policy allows providers to bypass claim submission to a prior payer. Use Group Code PR.",
         :effective_date =>"01/25/2009",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "230" =>
        {:code =>"230",
         :description =>
          "No available or correlating CPT/HCPCS code to describe this service. Note: Used only by Property and Casualty.",
         :effective_date =>"01/25/2009",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "231" =>
        {:code =>"231",
         :description =>
          "Mutually exclusive procedures cannot be done in the same day/setting. Note: Refer to the 835 Healthcare Policy Identification Segment (loop 2110 Service Payment Information  REF), if present.",
         :effective_date =>"07/01/2009",
         :deactivation_date =>"",
         :last_modified_date =>"09/20/2009",
         :notes =>""},
       "232" =>
        {:code =>"232",
         :description =>
          "Institutional Transfer Amount. Note - Applies to institutional claims only and explains the DRG amount difference when the patient care crosses multiple institutions.",
         :effective_date =>"11/01/2009",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "233" =>
        {:code =>"233",
         :description =>
          "Services/charges related to the treatment of a hospital-acquired condition or preventable medical error.",
         :effective_date =>"01/24/2010",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "234" =>
        {:code =>"234",
         :description =>
          "This procedure is not paid separately. At least one Remark Code must be provided (may be comprised of either the NCPDP Reject Reason Code, or Remittance Advice Remark Code that is not an ALERT.)",
         :effective_date =>"01/24/2010",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "235" =>
        {:code =>"235",
         :description =>"Sales Tax",
         :effective_date =>"06/06/2010",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "236" =>
        {:code =>"236",
         :description =>
          "This procedure or procedure/modifier combination is not compatible with another procedure or procedure/modifier combination provided on the same day according to the National Correct Coding Initiative.",
         :effective_date =>"01/30/2011",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "237" =>
        {:code =>"237",
         :description =>
          "Legislated/Regulatory Penalty. At least one Remark Code must be provided (may be comprised of either the NCPDP Reject Reason Code, or Remittance Advice Remark Code that is not an ALERT.)",
         :effective_date =>"06/05/2011",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "238" =>
        {:code =>"238",
         :description =>
          "Claim spans eligible and ineligible periods of coverage, this is the reduction for the ineligible period (use Group Code PR).",
         :effective_date =>"03/01/2012",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "239" =>
        {:code =>"239",
         :description =>
          "Claim spans eligible and ineligible periods of coverage. Rebill separate claims (use Group Code OA).",
         :effective_date =>"03/01/2012",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "A0" =>
        {:code =>"A0",
         :description =>"Patient refund amount.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "A1" =>
        {:code =>"A1",
         :description =>
          "Claim/Service denied. At least one Remark Code must be provided (may be comprised of either the NCPDP Reject Reason Code, or Remittance Advice Remark Code that is not an ALERT.)",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"09/20/2009",
         :notes =>""},
       "A2" =>
        {:code =>"A2",
         :description =>"Contractual adjustment.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"01/01/2008",
         :last_modified_date =>"02/28/2007",
         :notes =>
          "Use Code 45 with Group Code 'CO' or use another appropriate specific adjustment code."},
       "A3" =>
        {:code =>"A3",
         :description =>"Medicare Secondary Payer liability met.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"10/16/2003",
         :last_modified_date =>"",
         :notes =>""},
       "A4" =>
        {:code =>"A4",
         :description =>"Medicare Claim PPS Capital Day Outlier Amount.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"04/01/2008",
         :last_modified_date =>"09/30/2007",
         :notes =>""},
       "A5" =>
        {:code =>"A5",
         :description =>"Medicare Claim PPS Capital Cost Outlier Amount.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "A6" =>
        {:code =>"A6",
         :description =>
          "Prior hospitalization or 30 day transfer requirement not met.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "A7" =>
        {:code =>"A7",
         :description =>"Presumptive Payment Adjustment",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "A8" =>
        {:code =>"A8",
         :description =>"Ungroupable DRG.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"09/30/2007",
         :notes =>""},
       "B1" =>
        {:code =>"B1",
         :description =>"Non-covered visits.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "B2" =>
        {:code =>"B2",
         :description =>"Covered visits.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"10/16/2003",
         :last_modified_date =>"",
         :notes =>""},
       "B3" =>
        {:code =>"B3",
         :description =>"Covered charges.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"10/16/2003",
         :last_modified_date =>"",
         :notes =>""},
       "B4" =>
        {:code =>"B4",
         :description =>"Late filing penalty.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "B5" =>
        {:code =>"B5",
         :description =>
          "Coverage/program guidelines were not met or were exceeded.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"09/30/2007",
         :notes =>""},
       "B6" =>
        {:code =>"B6",
         :description =>
          "This payment is adjusted when performed/billed by this type of provider, by this type of provider in this type of facility, or by a provider of this specialty.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"02/01/2006",
         :last_modified_date =>"",
         :notes =>""},
       "B7" =>
        {:code =>"B7",
         :description =>
          "This provider was not certified/eligible to be paid for this procedure/service on this date of service. Note: Refer to the 835 Healthcare Policy Identification Segment (loop 2110 Service Payment Information  REF), if present.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"09/20/2009",
         :notes =>""},
       "B8" =>
        {:code =>"B8",
         :description =>
          "Alternative services were available, and should have been utilized. Note: Refer to the 835 Healthcare Policy Identification Segment (loop 2110 Service Payment Information  REF), if present.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"09/20/2009",
         :notes =>""},
       "B9" =>
        {:code =>"B9",
         :description =>"Patient is enrolled in a Hospice.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"09/30/2007",
         :notes =>""},
       "B10" =>
        {:code =>"B10",
         :description =>
          "Allowed amount has been reduced because a component of the basic procedure/test was paid. The beneficiary is not liable for more than the charge limit for the basic procedure/test.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "B11" =>
        {:code =>"B11",
         :description =>
          "The claim/service has been transferred to the proper payer/processor for processing. Claim/service not covered by this payer/processor.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "B12" =>
        {:code =>"B12",
         :description =>"Services not documented in patients' medical records.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "B13" =>
        {:code =>"B13",
         :description =>
          "Previously paid. Payment for this claim/service may have been provided in a previous payment.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""},
       "B14" =>
        {:code =>"B14",
         :description =>
          "Only one visit or consultation per physician per day is covered.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"09/30/2007",
         :notes =>""},
       "B15" =>
        {:code =>"B15",
         :description =>
          "This service/procedure requires that a qualifying service/procedure be received and covered. The qualifying other service/procedure has not been received/adjudicated. Note: Refer to the 835 Healthcare Policy Identification Segment (loop 2110 Service Payment Information  REF), if present.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"09/20/2009",
         :notes =>""},
       "B16" =>
        {:code =>"B16",
         :description =>"'New Patient' qualifications were not met.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"09/30/2007",
         :notes =>""},
       "B17" =>
        {:code =>"B17",
         :description =>
          "Payment adjusted because this service was not prescribed by a physician, not prescribed prior to delivery, the prescription is incomplete, or the prescription is not current.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"02/01/2006",
         :last_modified_date =>"",
         :notes =>""},
       "B18" =>
        {:code =>"B18",
         :description =>
          "This procedure code and modifier were invalid on the date of service.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"03/01/2009",
         :last_modified_date =>"09/21/2008",
         :notes =>""},
       "B19" =>
        {:code =>"B19",
         :description =>
          "Claim/service adjusted because of the finding of a Review Organization.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"10/16/2003",
         :last_modified_date =>"",
         :notes =>""},
       "B20" =>
        {:code =>"B20",
         :description =>
          "Procedure/service was partially or fully furnished by another provider.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"09/30/2007",
         :notes =>""},
       "B21" =>
        {:code =>"B21",
         :description =>
          "The charges were reduced because the service/care was partially furnished by another physician.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"10/16/2003",
         :last_modified_date =>"",
         :notes =>""},
       "B22" =>
        {:code =>"B22",
         :description =>"This payment is adjusted based on the diagnosis.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"02/28/2001",
         :notes =>""},
       "B23" =>
        {:code =>"B23",
         :description =>
          "Procedure billed is not authorized per your Clinical Laboratory Improvement Amendment (CLIA) proficiency test.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"",
         :last_modified_date =>"09/30/2007",
         :notes =>""},
       "D1" =>
        {:code =>"D1",
         :description =>
          "Claim/service denied. Level of subluxation is missing or inadequate.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"10/16/2003",
         :last_modified_date =>"",
         :notes =>"Use code 16 and remark codes if necessary."},
       "D2" =>
        {:code =>"D2",
         :description =>
          "Claim lacks the name, strength, or dosage of the drug furnished.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"10/16/2003",
         :last_modified_date =>"",
         :notes =>"Use code 16 and remark codes if necessary."},
       "D3" =>
        {:code =>"D3",
         :description =>
          "Claim/service denied because information to indicate if the patient owns the equipment that requires the part or supply was missing.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"10/16/2003",
         :last_modified_date =>"",
         :notes =>"Use code 16 and remark codes if necessary."},
       "D4" =>
        {:code =>"D4",
         :description =>
          "Claim/service does not indicate the period of time for which this will be needed.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"10/16/2003",
         :last_modified_date =>"",
         :notes =>"Use code 16 and remark codes if necessary."},
       "D5" =>
        {:code =>"D5",
         :description =>
          "Claim/service denied. Claim lacks individual lab codes included in the test.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"10/16/2003",
         :last_modified_date =>"",
         :notes =>"Use code 16 and remark codes if necessary."},
       "D6" =>
        {:code =>"D6",
         :description =>
          "Claim/service denied. Claim did not include patient's medical record for the service.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"10/16/2003",
         :last_modified_date =>"",
         :notes =>"Use code 16 and remark codes if necessary."},
       "D7" =>
        {:code =>"D7",
         :description =>
          "Claim/service denied. Claim lacks date of patient's most recent physician visit.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"10/16/2003",
         :last_modified_date =>"",
         :notes =>"Use code 16 and remark codes if necessary."},
       "D8" =>
        {:code =>"D8",
         :description =>
          "Claim/service denied. Claim lacks indicator that 'x-ray is available for review.'",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"10/16/2003",
         :last_modified_date =>"",
         :notes =>"Use code 16 and remark codes if necessary."},
       "D9" =>
        {:code =>"D9",
         :description =>
          "Claim/service denied. Claim lacks invoice or statement certifying the actual cost of the lens, less discounts or the type of intraocular lens used.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"10/16/2003",
         :last_modified_date =>"",
         :notes =>"Use code 16 and remark codes if necessary."},
       "D10" =>
        {:code =>"D10",
         :description =>
          "Claim/service denied. Completed physician financial relationship form not on file.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"10/16/2003",
         :last_modified_date =>"",
         :notes =>"Use code 17."},
       "D11" =>
        {:code =>"D11",
         :description =>"Claim lacks completed pacemaker registration form.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"10/16/2003",
         :last_modified_date =>"",
         :notes =>"Use code 17."},
       "D12" =>
        {:code =>"D12",
         :description =>
          "Claim/service denied. Claim does not identify who performed the purchased diagnostic test or the amount you were charged for the test.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"10/16/2003",
         :last_modified_date =>"",
         :notes =>"Use code 17."},
       "D13" =>
        {:code =>"D13",
         :description =>
          "Claim/service denied. Performed by a facility/supplier in which the ordering/referring physician has a financial interest.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"10/16/2003",
         :last_modified_date =>"",
         :notes =>"Use code 17."},
       "D14" =>
        {:code =>"D14",
         :description =>"Claim lacks indication that plan of treatment is on file.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"10/16/2003",
         :last_modified_date =>"",
         :notes =>"Use code 17."},
       "D15" =>
        {:code =>"D15",
         :description =>
          "Claim lacks indication that service was supervised or evaluated by a physician.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"10/16/2003",
         :last_modified_date =>"",
         :notes =>"Use code 17."},
       "D16" =>
        {:code =>"D16",
         :description =>"Claim lacks prior payer payment information.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"06/30/2007",
         :last_modified_date =>"",
         :notes =>"Use code 16 with appropriate claim payment remark code [N4]."},
       "D17" =>
        {:code =>"D17",
         :description =>"Claim/Service has invalid non-covered days.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"06/30/2007",
         :last_modified_date =>"",
         :notes =>"Use code 16 with appropriate claim payment remark code."},
       "D18" =>
        {:code =>"D18",
         :description =>"Claim/Service has missing diagnosis information.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"06/30/2007",
         :last_modified_date =>"",
         :notes =>"Use code 16 with appropriate claim payment remark code."},
       "D19" =>
        {:code =>"D19",
         :description =>
          "Claim/Service lacks Physician/Operative or other supporting documentation",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"06/30/2007",
         :last_modified_date =>"",
         :notes =>"Use code 16 with appropriate claim payment remark code."},
       "D20" =>
        {:code =>"D20",
         :description =>"Claim/Service missing service/product information.",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"06/30/2007",
         :last_modified_date =>"",
         :notes =>"Use code 16 with appropriate claim payment remark code."},
       "D21" =>
        {:code =>"D21",
         :description =>
          "This (these) diagnosis(es) is (are) missing or are invalid",
         :effective_date =>"01/01/1995",
         :deactivation_date =>"06/30/2007",
         :last_modified_date =>"",
         :notes =>""},
       "D22" =>
        {:code =>"D22",
         :description => "Reimbursement was adjusted for the reasons to be provided in separate correspondence. (Note: To be used for Workers' Compensation only) - Temporary code to be added for timeframe only until 01/01/2009. Another code to be established and/or for 06/2008 meeting for a revised code to replace or strategy to use another existing code",
         :effective_date =>"01/27/2008",
         :deactivation_date =>"01/01/2009",
         :last_modified_date =>"",
         :notes =>""},
       "D23" =>
        {:code =>"D23",
         :description => "This dual eligible patient is covered by Medicare Part D per Medicare Retro-Eligibility.  At least one Remark Code must be provided (may be comprised of either the NCPDP Reject Reason Code, or Remittance Advice Remark Code that is not an ALERT.)",
         :effective_date =>"11/01/2009",
         :deactivation_date =>"01/01/2012",
         :last_modified_date =>"",
         :notes =>""},
       "W1" =>
        {:code =>"W1",
         :description =>
          "Workers' compensation jurisdictional fee schedule adjustment. Note: If adjustment is at the Claim Level, the payer must send and the provider should refer to the 835 Class of Contract Code Identification Segment (Loop 2100 Other Claim Related Information REF). If adjustment is at the Line Level, the payer must send and the provider should refer to the 835 Healthcare Policy Identification Segment (loop 2110 Service Payment information REF).",
         :effective_date =>"02/29/2000",
         :deactivation_date =>"",
         :last_modified_date =>"10/17/2010",
         :notes =>""},
       "W2" =>
        {:code =>"W2",
         :description =>
          "Payment reduced or denied based on workers' compensation jurisdictional regulations or payment policies, use only if no other code is applicable.  Note: If adjustment is at the Claim Level, the payer must send and the provider should refer to the 835 Insurance Policy Number Segment (Loop 2100 Other Claim Related Information REF qualifier 'IG') for the jurisdictional regulation. If adjustment is at the Line Level, the payer must send and the provider should refer to the 835 Healthcare Policy Identification Segment (loop 2110 Service Payment information REF). To be used for Workers' Compensation only.",
         :effective_date =>"10/17/2010",
         :deactivation_date =>"",
         :last_modified_date =>"",
         :notes =>""}}

  end
end